package document.manager;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ShippingLabelRequired implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "State Code")
   private java.lang.String stateCode;
   @org.kie.api.definition.type.Label(value = "Is Shipping Label Required")
   private java.lang.Boolean isShippingLabelRequired;

   public ShippingLabelRequired()
   {
   }

   public java.lang.String getStateCode()
   {
      return this.stateCode;
   }

   public void setStateCode(java.lang.String stateCode)
   {
      this.stateCode = stateCode;
   }

   public java.lang.Boolean getIsShippingLabelRequired()
   {
      return this.isShippingLabelRequired;
   }

   public void setIsShippingLabelRequired(
         java.lang.Boolean isShippingLabelRequired)
   {
      this.isShippingLabelRequired = isShippingLabelRequired;
   }

   public ShippingLabelRequired(java.lang.String stateCode,
         java.lang.Boolean isShippingLabelRequired)
   {
      this.stateCode = stateCode;
      this.isShippingLabelRequired = isShippingLabelRequired;
   }

}